#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

# IMPORTANT! Keep the '-p' flag at the end of the DMENU and RMENU variables.
# Also, keep the '--prompt' flag at the end of the FMENU variable.
# These are needed as we use prompts in the scripts.
DMENU="dmenu -b -l 20 -p"
RMENU="rofi -dmenu -p"
FMENU="fzf --bind=enter:replace-query+print-query --border=rounded --margin=5% --color=dark --height 100% --reverse --header=$(basename "$0") --info=hidden --header-first --prompt"


## DEFAULT PROGRAMS
PDF_VIEWER="zathura"
DMBROWSER="brave"
DMTERM="alacritty -e"
DMEDITOR="nvim"
# DMEDITOR="${DMTERM} vim"
DMLOCKER='slock'

# dmscripts will notify you if your configuration is outdated.
# To shut it up uncomment this line.
# DM_SHUTUP="something" # NOTICE: This is currently experimental and will not work in (most) programs

# Set this variable up to a real file if you want dmscripts to provide a log of when
# and what has changed in your config (this can be an alternative to notifications)
DM_CONFIG_DIFF_LOGFILE="/dev/stderr" # NOTICE: experimental

# This case statement lets you change what the DMENU variable is for different scripts, so if you
# want a unique variable for each script you can
# syntax is as follows:
# "<ending-of-script>") DMENU="your variable here"
# *) should be left blank, global variables are defined above

# include -p in standard dmenu as we use prompts by default
case "${0##*-}" in
#  "colpick") DMENU="dmenu -i -p";;
#  "confedit") DMENU="dmenu -i -l 30 -p";;
#  "youtube") DMBROWSER="firefox";;
  *);;
esac

# "${0##*-}" means grab the 0th argument (which is always the path to the program) starting from the
# last dash. This gives us the word after the - which is what we are searching for in the case
# statement. ie dm-man -> man

# An awk equivalent is: 
# awk -F"-" '{print $NF}'
# Sadly cut has no easy equivalent

# TODO: Move almost all of these variables into the case statement
# TODO: Make some of the more useful ones general variables
# IE a pictures directory, an audio directory, config locations, etc

# dm-bookman 
bookman_show_source=1

# dm-sounds
sounds_dir="${HOME}/.config/dmscripts/dmsounds"

# dm-setbg
setbg_dir="/usr/share/backgrounds/dtos-backgrounds"
# setbg_dir="${HOME}/Pictures/Wallpapers"
# Set this to 1 if you want to use imv and wayland, 0 if you want to use sxiv
# Note that sxiv is X11 only, you need to mark the image you want to use.
use_imv=0 

# dm-maim
maim_dir="${HOME}/Screenshots"
maim_file_prefix="maim"

# dm-note
note_dir="${HOME}/.config/dmscripts/dmnote"


# Search engine config 
declare -Ag websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
websearch[brave]="https://search.brave.com/search?q="
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[google]="https://www.google.com/search?q="
# Information/News
websearch[bbcnews]="https://www.bbc.co.uk/search?q="
websearch[cnn]="https://www.cnn.com/search?q="
websearch[googlenews]="https://news.google.com/search?q="
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Online Shopping
websearch[amazon]="https://www.amazon.com/s?k="
# Linux
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[debianpkg]="https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
# Development
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
# Etc

# dm-youtube config
# Think of these as your "subscribed channels", name the channel in the square brackets then put the channel URL in the quotation marks
# Syntax: youtube_channels[name]="https://www.youtube.com/link/to/channel"

declare -Ag youtube_channels
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/featured"

# dm-radio config
# Your list of online radio stations for the dm-radio script.
# Syntax: radio_stations[name]="https://www.zeno.fm/radio/your-station"
# dmradio-volume ranges between -1 and 100 (for mplayer) or 0-100 (for mpv)

DMRADIOVOLUME="100"
declare -Ag radio_stations
radio_stations[Oldies Radio 50s-60s]="https://zeno.fm/radio/oldies-radio-50s-60s/"
radio_stations[Oldies Radio 70s]="https://zeno.fm/radio/oldies-radio-70s/"
radio_stations[Unlimited 80s]="https://zeno.fm/radio/unlimited80s/"
radio_stations[80s Hits]="https://zeno.fm/radio/80shits/"
radio_stations[90s Hits]="https://zeno.fm/radio/90s_HITS/"
radio_stations[2000s Pop]="https://zeno.fm/radio/2000s-pop/"
radio_stations[The 2000s]="https://zeno.fm/radio/the-2000s/"
radio_stations[Hits 2010s]="https://zeno.fm/radio/helia-hits-2010/"
radio_stations[Classical Radio]="https://zeno.fm/radio/classical-radio/"
radio_stations[Classical Relaxation]="https://zeno.fm/radio/radio-christmas-non-stop-classical/"
radio_stations[Classic Rock]="https://zeno.fm/radio/classic-rockdnb2sav8qs8uv/"
radio_stations[Gangsta49]="https://zeno.fm/radio/gangsta49/"
radio_stations[HipHop49]="https://zeno.fm/radio/hiphop49/"
radio_stations[Madhouse Country Radio]="https://zeno.fm/radio/madhouse-country-radio/"
radio_stations[PopMusic]="https://zeno.fm/radio/popmusic74vyurvmug0uv/"
radio_stations[PopStars]="https://zeno.fm/radio/popstars/"
radio_stations[RadioMetal]="https://zeno.fm/radio/radio-metal/"
radio_stations[RocknRoll Radio]="https://zeno.fm/radio/rocknroll-radio994c7517qs8uv/"

# dm-colpick config
declare -Ag colpick_list
colpick_list[black]="#282a36"
colpick_list[red]="#ff5555"
colpick_list[green]="#5af78e"
colpick_list[yellow]="#f1fa8c"
colpick_list[blue]="#57c7ff"
colpick_list[magenta]="#ff6ac1"
colpick_list[cyan]="#8be9fd"
colpick_list[white]="#f1f1f0"
colpick_list[orange]="#ffb86c"
colpick_list[purple]="#bd9cf9"

# dm-weather config

# Example: set the default search parameters to Texas, Paris and Kyiv
# weather_locations="Texas, United States
# Paris, France
# Kyiv, Ukraine"
weather_locations=""

# use the weather_opts variable to set additional flags:
# weather_opts="flag1&flag2&flag3=somevalue"

# for full details see: https://github.com/chubin/wttr.in

# current revision (do not touch unless you know what you're doing)
_revision=27
