[general]
import = ["/home/spectre/.config/alacritty/themes/night_owl.toml"]

[window]
opacity = 0.8 
decorations = "None"

[env]
TERM = "xterm-256color"

[cursor.style]
shape = "Block"

[font]
normal = { family = "Operator Mono", style = "Medium" }
bold = { family = "Operator Mono", style = "Bold" }
italic = { family = "Operator Mono", style = "Book Italic" }
bold_italic = { family = "Operator Mono", style = "Bold Italic" }

[window.dimensions]
columns = 140
lines = 27

[window.padding]
x = 17
y = 17
