#!/usr/bin/env bash
#
# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null

source_dmscripts_configs

if configs_are_different; then
    echo "$(date): configs are different" >>"$DM_CONFIG_DIFF_LOGFILE"
    sleep 1
fi

main() {

    # Getting the URL of the search engine we chose.
    url="https://ldoceonline.com/dictionary/"

    # Searching the chosen engine.
    query=$(${MENU} 'Enter word to lookup:')

    query="$(echo -n "${query}")"

    if ([ -z "$query" ]); then
	    query=$(xsel)
    fi
    # Display search results in web browser
    # shellcheck disable=SC2154
    ${DMBROWSER} "${url}${query}"
}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
