scan_timeout=100

[username]
style_user = "red bold"
style_root = "red bold"
format = "󰣇 [$user]($style) "
disabled = false
show_always = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold cyan) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
#success_symbol = "[➜](bold cyan) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

# configure directory
[directory]
read_only = " 🔒"
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "italic cyan"
#style = "bold italic yellow"


